// ─── O'zbekiston viloyatlari va ularning tuman/shaharlari ─────────────
// Talaba ro'yxatdan o'tishda "Viloyat" tanlaganda, "Tuman/Shahar"
// dropdown'i shu viloyatga tegishli ro'yxat bilan avtomatik yangilanadi.

const Map<String, List<String>> kRegionsWithDistricts = {
  'Andijon viloyati': [
    'Andijon shahri',
    'Andijon tumani',
    'Asaka tumani',
    'Baliqchi tumani',
    "Bo'z tumani",
    'Buloqboshi tumani',
    'Izboskan tumani',
    'Jalaquduq tumani',
    'Marhamat tumani',
    "Oltinko'l tumani",
    'Paxtaobod tumani',
    "Qo'rg'ontepa tumani",
    'Shahrixon tumani',
    "Ulug'nor tumani",
    'Xo\'jaobod tumani',
    'Xonobod shahri',
  ],
  'Buxoro viloyati': [
    'Buxoro shahri',
    'Buxoro tumani',
    "G'ijduvon tumani",
    'Jondor tumani',
    'Kogon shahri',
    'Kogon tumani',
    'Olot tumani',
    'Peshku tumani',
    "Qorako'l tumani",
    "Qorovulbozor tumani",
    'Romitan tumani',
    'Shofirkon tumani',
    'Vobkent tumani',
  ],
  "Farg'ona viloyati": [
    "Farg'ona shahri",
    "Marg'ilon shahri",
    "Qo'qon shahri",
    "Farg'ona tumani",
    "Bag'dod tumani",
    'Beshariq tumani',
    'Buvayda tumani',
    "Dang'ara tumani",
    'Furqat tumani',
    'Oltiariq tumani',
    'Quva tumani',
    "Qo'shtepa tumani",
    'Rishton tumani',
    "So'x tumani",
    'Toshloq tumani',
    "Uchko'prik tumani",
    "O'zbekiston tumani",
    'Yozyovon tumani',
  ],
  'Jizzax viloyati': [
    'Jizzax shahri',
    'Arnasoy tumani',
    'Baxmal tumani',
    "Do'stlik tumani",
    'Forish tumani',
    "G'allaorol tumani",
    'Jizzax tumani',
    "Mirzacho'l tumani",
    'Paxtakor tumani',
    'Zafarobod tumani',
    'Zarbdor tumani',
    'Zomin tumani',
  ],
  'Xorazm viloyati': [
    'Urganch shahri',
    "Bog'ot tumani",
    'Gurlan tumani',
    'Xazorasp tumani',
    'Xiva tumani',
    'Xonqa tumani',
    "Qo'shko'pir tumani",
    'Shovot tumani',
    'Urganch tumani',
    'Yangiariq tumani',
    'Yangibozor tumani',
  ],
  'Namangan viloyati': [
    'Namangan shahri',
    'Chortoq tumani',
    'Chust tumani',
    'Kosonsoy tumani',
    'Mingbuloq tumani',
    'Namangan tumani',
    "Norin tumani",
    'Pop tumani',
    "To'raqo'rg'on tumani",
    'Uychi tumani',
    "Uchqo'rg'on tumani",
    "Yangiqo'rg'on tumani",
  ],
  'Navoiy viloyati': [
    'Navoiy shahri',
    'Zarafshon shahri',
    'Konimex tumani',
    'Karmana tumani',
    'Navbahor tumani',
    'Nurota tumani',
    'Qiziltepa tumani',
    'Tomdi tumani',
    "Uchquduq tumani",
    'Xatirchi tumani',
  ],
  'Qashqadaryo viloyati': [
    'Qarshi shahri',
    'Shahrisabz shahri',
    'Chiroqchi tumani',
    'Dehqonobod tumani',
    "G'uzor tumani",
    'Kasbi tumani',
    'Kitob tumani',
    'Koson tumani',
    'Mirishkor tumani',
    'Muborak tumani',
    'Nishon tumani',
    'Qamashi tumani',
    'Qarshi tumani',
    'Shahrisabz tumani',
    "Yakkabog' tumani",
  ],
  "Qoraqalpog'iston Respublikasi": [
    'Nukus shahri',
    'Amudaryo tumani',
    'Beruniy tumani',
    'Chimboy tumani',
    "Ellikqal'a tumani",
    'Kegeyli tumani',
    "Mo'ynoq tumani",
    'Nukus tumani',
    "Qanliko'l tumani",
    "Qo'ng'irot tumani",
    "Qorao'zak tumani",
    'Shumanay tumani',
    "Taxtako'pir tumani",
    "To'rtko'l tumani",
    "Xo'jayli tumani",
  ],
  'Samarqand viloyati': [
    'Samarqand shahri',
    "Bulung'ur tumani",
    'Ishtixon tumani',
    'Jomboy tumani',
    "Kattaqo'rg'on shahri",
    "Kattaqo'rg'on tumani",
    'Narpay tumani',
    'Nurobod tumani',
    'Oqdaryo tumani',
    'Pastdarg\'om tumani',
    'Payariq tumani',
    'Paxtachi tumani',
    "Qo'shrabot tumani",
    'Samarqand tumani',
    'Toyloq tumani',
    'Urgut tumani',
  ],
  'Sirdaryo viloyati': [
    'Guliston shahri',
    'Yangiyer shahri',
    'Boyovut tumani',
    'Guliston tumani',
    'Mirzaobod tumani',
    'Oqoltin tumani',
    'Sardoba tumani',
    'Sayxunobod tumani',
    'Sirdaryo tumani',
    'Xovos tumani',
  ],
  'Surxondaryo viloyati': [
    'Termiz shahri',
    'Angor tumani',
    'Bandixon tumani',
    'Boysun tumani',
    'Denov tumani',
    "Jarqo'rg'on tumani",
    'Muzrabot tumani',
    'Oltinsoy tumani',
    'Qiziriq tumani',
    "Qumqo'rg'on tumani",
    'Sariosiyo tumani',
    'Sherobod tumani',
    'Shorchi tumani',
    'Termiz tumani',
    'Uzun tumani',
  ],
  'Toshkent viloyati': [
    'Angren shahri',
    'Bekobod shahri',
    'Chirchiq shahri',
    'Nurafshon shahri',
    'Ohangaron shahri',
    "Yangiyo'l shahri",
    'Bekobod tumani',
    "Bo'ka tumani",
    "Bo'stonliq tumani",
    'Chinoz tumani',
    'Qibray tumani',
    'Ohangaron tumani',
    "Oqqo'rg'on tumani",
    'Parkent tumani',
    'Piskent tumani',
    'Quyichirchiq tumani',
    'Toshkent tumani',
    'Urtachirchiq tumani',
    'Yuqorichirchiq tumani',
    'Zangiota tumani',
  ],
  'Toshkent shahri': [
    'Bektemir tumani',
    'Chilonzor tumani',
    "Mirzo Ulug'bek tumani",
    'Mirobod tumani',
    'Olmazor tumani',
    'Sergeli tumani',
    'Shayxontohur tumani',
    'Uchtepa tumani',
    'Yakkasaroy tumani',
    'Yangihayot tumani',
    'Yashnobod tumani',
    'Yunusobod tumani',
  ],
};

const List<String> kRegions = [
  'Andijon viloyati',
  'Buxoro viloyati',
  "Farg'ona viloyati",
  'Jizzax viloyati',
  'Xorazm viloyati',
  'Namangan viloyati',
  'Navoiy viloyati',
  'Qashqadaryo viloyati',
  "Qoraqalpog'iston Respublikasi",
  'Samarqand viloyati',
  'Sirdaryo viloyati',
  'Surxondaryo viloyati',
  'Toshkent viloyati',
  'Toshkent shahri',
];
